image: barichello/godot-ci:4.4

variables:
  EXPORT_NAME: test-project
  PROJECT_PATH: test-project

stages:
  - export
  - deploy

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows 