class_name Player
extends RefCounted

var name:String = ""
var photo:Image
var lobbyIndex:int
var id:int # id is generated by connecting to server via websocket

func _init(newName:String = "") -> void:
	name=newName
